camel:
  springboot:
    name: Rest-API-Endpoints-Frontend-Backend-Mapping
  servlet:
    mapping:
      context-path: /*
  rest:
    context-path: /

server:
  port: 8080
  
CreditCard:
  host: ${CREDITCARD_HOST}
  contextPath: ${CREDITCARD_CONTEXTPATH}

configStoreConnector:
  apiKeyName: configstore
  host: ${CONFIGSTORECONNECTOR_HOST}
  contextPath: ${CONFIGSTORECONNECTOR_CONTEXTPATH} 

encryption:
  apiKeyName: encryption_handler
  secretKey: ${ENCRYPTION_SECRET_KEY}
  
creditCardMock:
  host: ${CREDIT_CARD_MOCK_HOST}
  contextPath: ${CREDIT_CARD_MOCK_CONTEXTPATH}
  
newCreditCardMock:
  host: ${NEW_CC_MOCK_HOST}
  contextPath: ${NEW_CC_MOCK_CONTEXTPATH}